body
{
font-family: Verdana, Helvetica, Arial, sans-serif;
font-size: 12px;
}
h1
{
font-size: 16px;	
}
p
{
font-size: 12px;
}
hr
{
height: 1px;
}	
table
{
width: 100%;
/*
	margin-left: 10px;
	border-left: 2px solid silver;
*/
}
table .left
{
width: 30%;
}
table .right
{
width: 70%;
}
table td,
table th
{
padding-top: 3px;
padding-bottom: 3px;
padding-left: 10px;
font-size: 12px;
color: #000000;
vertical-align:top;
text-align:left;
}
.footer
{
font-size: 10px;
font-style: italic;
color: gray;
}	

#recaptcha_table td{padding: 0 !important;}
